// <auto-generated />
using System;
using BallSport.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BallSport.Infrastructure.Migrations
{
    [DbContext(typeof(Sep490G19v1Context))]
    [Migration("20251114174532_AddFieldImagesTable")]
    partial class AddFieldImagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BallSport.Infrastructure.Models.BlogPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PostId")
                        .HasName("PK__BlogPost__AA12603833AB0D25");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("HasOpponent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MatchRequestId")
                        .HasColumnType("int")
                        .HasColumnName("MatchRequestID");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Qrcode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("QRCode");

                    b.Property<DateTime?>("QrexpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("QRExpiresAt");

                    b.Property<decimal?>("RemainingAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD3F1D6103");

                    b.HasIndex("MatchRequestId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.BookingCancellation", b =>
                {
                    b.Property<int>("CancellationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CancellationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CancelledBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("PenaltyAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("CancellationId")
                        .HasName("PK__BookingC__6A2D9A1AFAD0F417");

                    b.HasIndex("BookingId");

                    b.HasIndex("RequestId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("BookingCancellations");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.BookingCancellationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<decimal?>("FinalRefundAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("RequestReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RequestStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("RequestedByRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("RequestedByUserID");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReversedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ReversedByUserID");

                    b.Property<DateTime?>("UndoAllowedUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId")
                        .HasName("PK__BookingC__33A8519A54076F12");

                    b.HasIndex("BookingId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReversedByUserId");

                    b.ToTable("BookingCancellationRequests");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.CancellationPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PolicyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<int>("CancelBeforeHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("FieldID");

                    b.Property<decimal?>("OwnerPenaltyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RefundRate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PolicyId")
                        .HasName("PK__Cancella__2E1339446C8E5B6C");

                    b.HasIndex("FieldId");

                    b.ToTable("CancellationPolicies");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentCommentID");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CommentId")
                        .HasName("PK__Comments__C3B4DFAAB7F9B484");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.DepositPolicy", b =>
                {
                    b.Property<int>("DepositPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepositPolicyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepositPolicyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DepositPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("FieldID");

                    b.Property<decimal?>("MaxDeposit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MinDeposit")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DepositPolicyId")
                        .HasName("PK__DepositP__0B7CD7A3AFACB82D");

                    b.HasIndex("FieldId");

                    b.ToTable("DepositPolicies");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FieldID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("int")
                        .HasColumnName("BankAccountID");

                    b.Property<int?>("ComplexId")
                        .HasColumnType("int")
                        .HasColumnName("ComplexID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrassType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PricePerHour")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("FieldId")
                        .HasName("PK__Fields__C8B6FF273AB66C90");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ComplexId");

                    b.HasIndex("TypeId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldComplex", b =>
                {
                    b.Property<int>("ComplexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComplexID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplexId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("ComplexId")
                        .HasName("PK__FieldCom__E14B3DF668A4569F");

                    b.HasIndex("OwnerId");

                    b.ToTable("FieldComplexes");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldImages");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PriceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<int?>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("FieldID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    b.HasKey("PriceId")
                        .HasName("PK__FieldPri__4957584F6417A502");

                    b.HasIndex("SlotId");

                    b.HasIndex(new[] { "FieldId", "SlotId" }, "UQ__FieldPri__2817DB823439E8DC")
                        .IsUnique()
                        .HasFilter("[FieldID] IS NOT NULL AND [SlotID] IS NOT NULL");

                    b.ToTable("FieldPrices");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("FieldID");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.HasKey("ScheduleId")
                        .HasName("PK__FieldSch__9C8A5B69C9B647FD");

                    b.HasIndex("SlotId");

                    b.HasIndex(new[] { "FieldId", "Date", "SlotId" }, "UQ__FieldSch__F1CF6ABC02AE2AE5")
                        .IsUnique()
                        .HasFilter("[FieldID] IS NOT NULL AND [SlotID] IS NOT NULL");

                    b.ToTable("FieldSchedules");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId")
                        .HasName("PK__FieldTyp__516F03952DB61ED1");

                    b.HasIndex(new[] { "TypeName" }, "UQ__FieldTyp__D4E7DFA8A98A70C9")
                        .IsUnique();

                    b.ToTable("FieldTypes");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.MatchParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParticipantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<bool?>("IsCreator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MatchRequestId")
                        .HasColumnType("int")
                        .HasColumnName("MatchRequestID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ParticipantId")
                        .HasName("PK__MatchPar__7227997E0CC0A8DB");

                    b.HasIndex("MatchRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.MatchRequest", b =>
                {
                    b.Property<int>("MatchRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchRequestId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("MatchRequestId")
                        .HasName("PK__MatchReq__AE45CD76F9ECB289");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("MatchRequests");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E327469AD80");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.OwnerBankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BankAccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankAccountId"));

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BankAccountId")
                        .HasName("PK__OwnerBan__4FC8E7416736DED5");

                    b.HasIndex("OwnerId");

                    b.ToTable("OwnerBankAccounts");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Method")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PayOS");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayOrderInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PayUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayURL");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A580D32C6B5");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "OrderCode" }, "UQ_Payments_OrderCode")
                        .IsUnique()
                        .HasFilter("[OrderCode] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.PlayerBankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BankAccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankAccountId"));

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BankAccountId")
                        .HasName("PK__PlayerBa__4FC8E741E8399AB7");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerBankAccounts");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.PlayerMatchHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MatchRequestId")
                        .HasColumnType("int")
                        .HasColumnName("MatchRequestID");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("HistoryId")
                        .HasName("PK__PlayerMa__4D7B4ADD11DF0DB5");

                    b.HasIndex("MatchRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerMatchHistory", (string)null);
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("FieldID");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MediaURL");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PostId")
                        .HasName("PK__Posts__AA1260385ACE9BE0");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.PostLike", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LikeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LikeId")
                        .HasName("PK__PostLike__A2922CF4D8340BB2");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "UQ_PostLikes")
                        .IsUnique();

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int")
                        .HasColumnName("ReporterID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__D5BD48E53AE7A2FF");

                    b.HasIndex("HandledBy");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A38EC6744");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B616012173E19")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.SystemNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("InsUrgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NotificationType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SentBy")
                        .HasColumnType("int");

                    b.Property<string>("SentToRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SentToSpecificUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NotificationId")
                        .HasName("PK__SystemNo__20CF2E3247B2B39F");

                    b.HasIndex("SentBy");

                    b.ToTable("SystemNotifications");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("PreferredPositions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreferredSkillLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamId")
                        .HasName("PK__Teams__123AE7B9F41C7002");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.TeamJoinRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RespondedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RequestId")
                        .HasName("PK__TeamJoin__33A8519AF308DD09");

                    b.HasIndex("RespondedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamJoinRequests");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.TimeSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("SlotName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId")
                        .HasName("PK__TimeSlot__0A124A4FB1680F1C");

                    b.HasIndex(new[] { "StartTime", "EndTime" }, "UQ__TimeSlot__F4AF5A9C54149FFE")
                        .IsUnique();

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACF80E6B0E");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053449DCA7A5")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("bio");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferredPositions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SkillLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ProfileId")
                        .HasName("PK__UserProf__290C888465AA0478");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserProf__1788CCAD01035ECC")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserRoleId")
                        .HasName("PK__UserRole__3D978A55A5AFEB15");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "UQ__UserRole__AF27604EA2C5F7A0")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL AND [RoleID] IS NOT NULL");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.ViolationReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("int")
                        .HasColumnName("ReportedUserID");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int")
                        .HasColumnName("ReporterID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReportId")
                        .HasName("PK__Violatio__D5BD48E5023AD08D");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("ViolationReports");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.BlogPost", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__BlogPosts__Autho__236943A5");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Booking", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.MatchRequest", "MatchRequest")
                        .WithMany("Bookings")
                        .HasForeignKey("MatchRequestId")
                        .HasConstraintName("FK_Bookings_MatchRequests");

                    b.HasOne("BallSport.Infrastructure.Models.FieldSchedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Schedu__797309D9");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__UserID__787EE5A0");

                    b.Navigation("MatchRequest");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.BookingCancellation", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Booking", "Booking")
                        .WithMany("BookingCancellations")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingCa__Booki__114A936A");

                    b.HasOne("BallSport.Infrastructure.Models.BookingCancellationRequest", "Request")
                        .WithMany("BookingCancellations")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__BookingCa__Reque__123EB7A3");

                    b.HasOne("BallSport.Infrastructure.Models.User", "VerifiedByNavigation")
                        .WithMany("BookingCancellations")
                        .HasForeignKey("VerifiedBy")
                        .HasConstraintName("FK__BookingCa__Verif__151B244E");

                    b.Navigation("Booking");

                    b.Navigation("Request");

                    b.Navigation("VerifiedByNavigation");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.BookingCancellationRequest", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Booking", "Booking")
                        .WithMany("BookingCancellationRequests")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingCa__Booki__0A9D95DB");

                    b.HasOne("BallSport.Infrastructure.Models.User", "RequestedByUser")
                        .WithMany("BookingCancellationRequestRequestedByUsers")
                        .HasForeignKey("RequestedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingCa__Reque__0B91BA14");

                    b.HasOne("BallSport.Infrastructure.Models.User", "ReversedByUser")
                        .WithMany("BookingCancellationRequestReversedByUsers")
                        .HasForeignKey("ReversedByUserId")
                        .HasConstraintName("FK__BookingCa__Rever__0E6E26BF");

                    b.Navigation("Booking");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReversedByUser");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.CancellationPolicy", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Field", "Field")
                        .WithMany("CancellationPolicies")
                        .HasForeignKey("FieldId")
                        .IsRequired()
                        .HasConstraintName("FK__Cancellat__Field__05D8E0BE");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Comment", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK_Comments_Parent");

                    b.HasOne("BallSport.Infrastructure.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Posts");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Users");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.DepositPolicy", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Field", "Field")
                        .WithMany("DepositPolicies")
                        .HasForeignKey("FieldId")
                        .IsRequired()
                        .HasConstraintName("FK__DepositPo__Field__74AE54BC");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Field", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.OwnerBankAccount", "BankAccount")
                        .WithMany("Fields")
                        .HasForeignKey("BankAccountId")
                        .HasConstraintName("FK_Fields_OwnerBankAccounts");

                    b.HasOne("BallSport.Infrastructure.Models.FieldComplex", "Complex")
                        .WithMany("Fields")
                        .HasForeignKey("ComplexId")
                        .HasConstraintName("FK__Fields__ComplexI__619B8048");

                    b.HasOne("BallSport.Infrastructure.Models.FieldType", "Type")
                        .WithMany("Fields")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__Fields__TypeID__628FA481");

                    b.Navigation("BankAccount");

                    b.Navigation("Complex");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldComplex", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "Owner")
                        .WithMany("FieldComplexes")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK__FieldComp__Owner__5CD6CB2B");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldImage", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Field", "Field")
                        .WithMany("FieldImages")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldPrice", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Field", "Field")
                        .WithMany("FieldPrices")
                        .HasForeignKey("FieldId")
                        .HasConstraintName("FK__FieldPric__Field__70DDC3D8");

                    b.HasOne("BallSport.Infrastructure.Models.TimeSlot", "Slot")
                        .WithMany("FieldPrices")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK__FieldPric__SlotI__71D1E811");

                    b.Navigation("Field");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldSchedule", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Field", "Field")
                        .WithMany("FieldSchedules")
                        .HasForeignKey("FieldId")
                        .HasConstraintName("FK__FieldSche__Field__6B24EA82");

                    b.HasOne("BallSport.Infrastructure.Models.TimeSlot", "Slot")
                        .WithMany("FieldSchedules")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK__FieldSche__SlotI__6C190EBB");

                    b.Navigation("Field");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.MatchParticipant", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.MatchRequest", "MatchRequest")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("MatchRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__MatchPart__Match__3B40CD36");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__MatchPart__UserI__3C34F16F");

                    b.Navigation("MatchRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.MatchRequest", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Booking", "Booking")
                        .WithMany("MatchRequests")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__MatchRequ__Booki__3493CFA7");

                    b.HasOne("BallSport.Infrastructure.Models.User", "CreatedByNavigation")
                        .WithMany("MatchRequests")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__MatchRequ__Creat__3587F3E0");

                    b.Navigation("Booking");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Notification", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.OwnerBankAccount", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "Owner")
                        .WithMany("OwnerBankAccounts")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__OwnerBank__Owner__756D6ECB");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Payment", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Payments__Bookin__00200768");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.PlayerBankAccount", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("PlayerBankAccounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerBan__UserI__1B9317B3");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.PlayerMatchHistory", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.MatchRequest", "MatchRequest")
                        .WithMany("PlayerMatchHistories")
                        .HasForeignKey("MatchRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerMat__Match__41EDCAC5");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("PlayerMatchHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerMat__UserI__40F9A68C");

                    b.Navigation("MatchRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Post", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Field", "Field")
                        .WithMany("Posts")
                        .HasForeignKey("FieldId")
                        .HasConstraintName("FK_Posts_Fields");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Users");

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.PostLike", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_PostLikes_Posts");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PostLikes_Users");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Report", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "HandledByNavigation")
                        .WithMany("ReportHandledByNavigations")
                        .HasForeignKey("HandledBy")
                        .HasConstraintName("FK_Reports_Admin");

                    b.HasOne("BallSport.Infrastructure.Models.User", "Reporter")
                        .WithMany("ReportReporters")
                        .HasForeignKey("ReporterId")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_Reporter");

                    b.Navigation("HandledByNavigation");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.SystemNotification", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "SentByNavigation")
                        .WithMany("SystemNotifications")
                        .HasForeignKey("SentBy")
                        .IsRequired()
                        .HasConstraintName("FK__SystemNot__SentB__19DFD96B");

                    b.Navigation("SentByNavigation");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Team", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "CreatedByNavigation")
                        .WithMany("Teams")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Teams__CreatedBy__282DF8C2");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.TeamJoinRequest", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "RespondedByNavigation")
                        .WithMany("TeamJoinRequestRespondedByNavigations")
                        .HasForeignKey("RespondedBy")
                        .HasConstraintName("FK__TeamJoinR__Respo__31B762FC");

                    b.HasOne("BallSport.Infrastructure.Models.Team", "Team")
                        .WithMany("TeamJoinRequests")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__TeamJoinR__TeamI__2DE6D218");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("TeamJoinRequestUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__TeamJoinR__UserI__2EDAF651");

                    b.Navigation("RespondedByNavigation");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.UserProfile", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("BallSport.Infrastructure.Models.UserProfile", "UserId")
                        .HasConstraintName("FK__UserProfi__UserI__571DF1D5");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.UserRole", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__UserRoles__RoleI__534D60F1");

                    b.HasOne("BallSport.Infrastructure.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserRoles__UserI__52593CB8");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.ViolationReport", b =>
                {
                    b.HasOne("BallSport.Infrastructure.Models.User", "ReportedUser")
                        .WithMany("ViolationReportReportedUsers")
                        .HasForeignKey("ReportedUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Violation__Repor__1DB06A4F");

                    b.HasOne("BallSport.Infrastructure.Models.User", "Reporter")
                        .WithMany("ViolationReportReporters")
                        .HasForeignKey("ReporterId")
                        .IsRequired()
                        .HasConstraintName("FK__Violation__Repor__1EA48E88");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Booking", b =>
                {
                    b.Navigation("BookingCancellationRequests");

                    b.Navigation("BookingCancellations");

                    b.Navigation("MatchRequests");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.BookingCancellationRequest", b =>
                {
                    b.Navigation("BookingCancellations");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Comment", b =>
                {
                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Field", b =>
                {
                    b.Navigation("CancellationPolicies");

                    b.Navigation("DepositPolicies");

                    b.Navigation("FieldImages");

                    b.Navigation("FieldPrices");

                    b.Navigation("FieldSchedules");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldComplex", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.FieldType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.MatchRequest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MatchParticipants");

                    b.Navigation("PlayerMatchHistories");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.OwnerBankAccount", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostLikes");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.Team", b =>
                {
                    b.Navigation("TeamJoinRequests");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.TimeSlot", b =>
                {
                    b.Navigation("FieldPrices");

                    b.Navigation("FieldSchedules");
                });

            modelBuilder.Entity("BallSport.Infrastructure.Models.User", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("BookingCancellationRequestRequestedByUsers");

                    b.Navigation("BookingCancellationRequestReversedByUsers");

                    b.Navigation("BookingCancellations");

                    b.Navigation("Bookings");

                    b.Navigation("Comments");

                    b.Navigation("FieldComplexes");

                    b.Navigation("MatchParticipants");

                    b.Navigation("MatchRequests");

                    b.Navigation("Notifications");

                    b.Navigation("OwnerBankAccounts");

                    b.Navigation("PlayerBankAccounts");

                    b.Navigation("PlayerMatchHistories");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("ReportHandledByNavigations");

                    b.Navigation("ReportReporters");

                    b.Navigation("SystemNotifications");

                    b.Navigation("TeamJoinRequestRespondedByNavigations");

                    b.Navigation("TeamJoinRequestUsers");

                    b.Navigation("Teams");

                    b.Navigation("UserProfile");

                    b.Navigation("UserRoles");

                    b.Navigation("ViolationReportReportedUsers");

                    b.Navigation("ViolationReportReporters");
                });
#pragma warning restore 612, 618
        }
    }
}
